version: "3.7"

services:
  orientdb:
    image: 305402192421.dkr.ecr.sa-east-1.amazonaws.com/sibila-orientdb:latest
    container_name: sibila-orientdb
    restart: always
    environment:
      - ORIENTDB_OPTS_MEMORY=-Xmx512m
    volumes:
      - /home/ec2-user/data/orientdb/databases:/var/lib/orientdb/data
    ports:
      - "2424:2424"
      - "2480:2480"
    networks:
      sibila_net:
        ipv4_address: 172.28.1.1
  sibila:
    image: 'mcasatti/sibila-fastapi:latest'
    container_name: sibila-fastapi
    restart: always
    ports:
      - '8000:8000'
    environment:
      - PB_DB_HOST=http://172.28.1.1 
      - PB_DB_PORT=2480 
      - PB_DB_USER=admin 
      - PB_DB_PASS=admin 
      - PB_LISTENING_PORT=8000
    depends_on:
      - orientdb
    networks:
      sibila_net:
        ipv4_address: 172.28.1.2
volumes:
  orientdb_data: {}

networks:
  sibila_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

